### ISSUE TITLE
How to compile or set new Dataref

### ISSUE THREAD

**Issue by jvbraganca** [nskillen/XP11_VA_Link#1]
Hello Nathan,

Thank you for putting your time into this plugin. I have a few questions, how can I compile the CPP code into X-plane's plugin? And how should I add new commands to Voice Attack so it sets my heading in a specific direction, for example? Reading the README file I got familiar with the syntax but can't figure out where to put it. 

`set;sim/cockpit/autopilot/heading[;float;180]`

**Comment by nskillen** [comment]
Hi @jvbraganca,

To build you'll need to download the X-Plane 11 Plugin SDK from here:
https://developer.x-plane.com/sdk/plugin-sdk-downloads/

As far as I know, the latest version _should_ work. I'm afraid that I'm not at my development box for the time being, so I can't test. If it doesn't, download version 3.0.1, as that's the one I used.

In the downloaded zip, is a folder named `SDK`. In there, is a folder called `CHeaders`. Extract the contents of that folder to a new folder named `XP11/include` in the root of the project (eg, if you have `C:\dev\XP11_VA_Link\XP11_VA_Link.sln`, then you want to end up with `C:\dev\XP11_VA_Link\XP11\include`.
Also in the `SDK` folder is another folder named `Libraries/Win`. Extract the contents of that to `XP11/lib`.

Now you should be able to build the project. Open in Visual Studio, in the `Build` menu, select `Build Solution`.

**For the X-Plane 11 plugin:**

I _think_, that when you build the project the X-Plane 11 plugin should be auto-copied into the X-Plane 11 plugin folder. If that doesn't work, you should see an error about copying the file in visual studio. If that happens, look inside `x64/Debug` or `x64/Release` folder for a file named `XP11_VALink.xpl`. Copy that file to the folder `C:\Program Files (x86)\Steam\steamapps\common\X-Plane 11\Resources\plugins\XP11_VALink\win_x64` (adjust as needed if you didn't get X-Plane 11 from Steam).

**For VoiceAttack:**

When you build the solution, the VoiceAttack plugin should be built in `VoiceAttack/bin/Debug` (or `VoiceAttack/bin/Release` depending on which you built). As with the X-Plane plugin, visual studio will attempt to copy it to your VoiceAttack installation (assuming that you bought it on steam). If that doesn't work you'll see an error message in visual studio. In that case, take the `XP11_VA_Link.dll` file from the build directory above, and copy it to `Applications\XP11_VA_Link\XP11_VA_Link.dll` inside your VoiceAttack install folder.

When you start VoiceAttack, if you go to settings, then on the `General` tab, you should have `Enable Plugin Support` checked. If you open the Plugin Manager, you should see XP11_VA_Link listed there.
![image](https://user-images.githubusercontent.com/120346/103471910-ad441580-4d43-11eb-8a2f-e1269ab0e3f9.png)

Now that we've got that out of the way, time to set a specific value for a dataref...

![image](https://user-images.githubusercontent.com/120346/103472021-3871db00-4d45-11eb-8bb7-607a403adff1.png)

This is probably the command you'd want. A few things to note
* VoiceAttack dynamic commands expand within the Windows Speech-recognition system into one command per option, so you'll want to avoid supporting the heading range of `[0..360]` degrees, because that would be effectively 360 separate commands. The range of `[0..24,15]` that I used here will generate 25 commands, each 15 degrees apart (the number after the comma multiplies each number in the range, so this expands to `[0,15,30,45,...,345,360]`
* You have to manually specify the type of data to send to X-Plane (`1 = Integer, 2 = Float, 4 = Double, 32 = Data`). Set the variable `datarefType` to the appropriate value for the data you're sending (probably `1 = Integer` in your case.
* The command mentioned `Set Dataref` in the last step isn't built into VoiceAttack, it's a helper I built myself. You'll probably want to make something like it because it's helpful for properly sending variables to the plugin. I'll provide more details below.

![image](https://user-images.githubusercontent.com/120346/103472129-e7fb7d00-4d46-11eb-906a-36a2cded35e8.png)

This is my `Set Dataref` command. I have defined one section for each value in `datarefType`. The `Execute external plugin` call is what actually triggers the communication with X-Plane.

![image](https://user-images.githubusercontent.com/120346/103472158-445e9c80-4d47-11eb-9f7e-a6a30bae8c72.png)

This is how you set a value for an int-type dataref. Two important things here:
* First, always remember to set the `Plugin context` to `SetDataref`. That's how the actual plugin knows what to do.
* Second is that `datarefValue` is added to the `Integer variables` section. So is `datarefType`, but it will always be there, since it's always an integer. For `datarefType=2 (Float)` or `datarefType=4 (Double)`, then `datarefValue` should go in `Decimal variables`, and for `datarefType=32 (Data)` it goes in `Text variables`. Make sure to check the box for `Wait for the plugin function to finish before continuing`.

![image](https://user-images.githubusercontent.com/120346/103472189-d4044b00-4d47-11eb-8e5a-2aa4f135d1d2.png)

This is my `Get Dataref` helper. Much simpler. From what I've already explained in `Set Dataref` you should be able to figure out what's going on here.

I hope this is enough to get you up and running.

**Comment by jvbraganca** [comment]
Hello again @nskillen, thank you so much for this guide. I was able to compile the Voice Attack plugin without any problems but when I tried to build the X-plane plugin I got the following error:

```bash
Rebuild started...
1>------ Rebuild All started: Project: XPlane11, Configuration: Debug x64 ------
1>pch.cpp
1>Plugin.cpp
1>DataCache.cpp
1>EnvData.cpp
1>Link.cpp
1>D:\Documentos\Programacao\X-plane\XP11_VA_Link\XPlane11\src\xp11_va\Link.cpp(237,63): warning C4267: 'argument': conversion from 'size_t' to 'int', possible loss of data
1>D:\Documentos\Programacao\X-plane\XP11_VA_Link\XPlane11\src\xp11_va\Link.cpp(240,61): warning C4267: 'argument': conversion from 'size_t' to 'int', possible loss of data
1>D:\Documentos\Programacao\X-plane\XP11_VA_Link\XPlane11\src\xp11_va\Link.cpp(243,61): warning C4267: 'argument': conversion from 'size_t' to 'int', possible loss of data
1>Logger.cpp
1>Pipe.cpp
1>WinPipe.cpp
1>D:\Documentos\Programacao\X-plane\XP11_VA_Link\XPlane11\src\xp11_va\platform\windows\WinPipe.cpp(104,6): warning C4267: 'argument': conversion from 'size_t' to 'DWORD', possible loss of data
1>Generating Code...
1>   Creating library D:\Documentos\Programacao\X-plane\XP11_VA_Link\x64\Debug\XP11_VA_Link.lib and object D:\Documentos\Programacao\X-plane\XP11_VA_Link\x64\Debug\XP11_VA_Link.exp
1>XPlane11.vcxproj -> D:\Documentos\Programacao\X-plane\XP11_VA_Link\x64\Debug\XP11_VA_Link.xpl
1>The system cannot find the path specified.
1>        0 file(s) copied.
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(153,5): error MSB3073: The command "copy "D:\Documentos\Programacao\X-plane\XP11_VA_Link\x64\Debug\XP11_VA_Link.xpl" "D:\Program Files (x86)\Steam\Steamapps\common\X-Plane 11\Resources\plugins\XP11_VA_Link\win_x64\XP11_VA_Link.xpl"
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(153,5): error MSB3073: :VCEnd" exited with code 1.
1>Done building project "XPlane11.vcxproj" -- FAILED.
========== Rebuild All: 0 succeeded, 1 failed, 0 skipped ==========
```
But, I found the `XP11_VA_Link.xpl` on `.\XP11_VA_Link\x64\Debug` folder. So I moved it to the plugins folder under the following directory `D:\Program Files (x86)\Steam\steamapps\common\X-Plane 11\Resources\plugins\XP11_VALink\win_x64\XP11_VA_Link.xpl`.

I opened X-plane and tried to run the commands as described by you. Here are some screenshots of the scripts I made following the one you posted:

![image](https://user-images.githubusercontent.com/16918085/103473204-c31dfe80-4d74-11eb-9361-31f6cf7353c1.png)
(I tried to use broken numbers instead of 15 degrees spaced ones)

The Set Dataref Helper:
![image](https://user-images.githubusercontent.com/16918085/103473209-d8932880-4d74-11eb-8712-d8c3a946f94f.png)

And the log:
![image](https://user-images.githubusercontent.com/16918085/103473212-de890980-4d74-11eb-9cb5-80b25734bef7.png)
I wonder if it's normal for the values being shown as not set.

Could it be a problem with the X-Plane's plugin compilation or I might be doing something wrong? If the second one might be the case how could I debug it? 

PS: As soon as I finish a successful compilation I will open a PR so it's easier for the users to use your plugin.

**Comment by jvbraganca** [comment]
Oh, also the plugin is not being shown on the X-Plane's plugin menu. Is it normal?

![image](https://user-images.githubusercontent.com/16918085/103473246-535c4380-4d75-11eb-9e40-bceea3e6c014.png)

**Comment by nskillen** [comment]
Hi @jvbraganca

I've got X-Plane downloading so that I can test some things here, but it will be several hours, as I'm not in the city currently.

In the meantime, the only suggestions I can make are:

1. Ensure the name of your folder in the X-Plane plugins folder matches the filename. I believe that may be required.
What I mean is, right now you have this:
`D:\Program Files (x86)\Steam\steamapps\common\X-Plane 11\Resources\plugins\XP11_VALink\win_x64\XP11_VA_Link.xpl`
Try changing to either this:
`D:\Program Files (x86)\Steam\steamapps\common\X-Plane 11\Resources\plugins\XP11_VA_Link\win_x64\XP11_VA_Link.xpl`
or this:
`D:\Program Files (x86)\Steam\steamapps\common\X-Plane 11\Resources\plugins\XP11_VALink\win_x64\XP11_VALink.xpl`

2. Modify the build to explicitly support X-Plane 11.50+
    1. Open Visual Studio
    2. Right-click on the `XPlane11` project and select `Properties`
    3. Set the configuration to `Debug` or `Release`, as you prefer
    4. In the `Configuration Properties` tree, drill-down to `Configuration Properties > C/C++ > Preprocessor`
    5. On the first item in the right-hand side, `Preprocessor Definitions`, click the down arrow and select `<Edit...>`
    6. add `XPLM301` and `XPLM303` to the list, each on their own line
    7. Close the properties pane by clicking `OK`
    8. Rebuild by going to the `Build` menu, and selecting `Rebuild Solution`

If it still doesn't work, could you `Show Plugin Admin` (top entry of your last screenshot there) and screenshot that for me? I can't remember whether a failed load will show up in there.

Also, you could take a look at X-Plane's log file, which should be located at `D:\Program Files (x86)\Steam\steamapps\common\X-Plane 11\log.txt`. Maybe look through that file for occurrences of the text `XP11_VA_Link`, see if anything pops up.

Lastly, if you want to get rid of the build errors, open the `XPlane11` project properties pane, navigate to `Configuration Properties > Build Events > Post-Build Event` and `<Edit...>` the `Command Line` value to properly copy the file to your X-Plane plugins folder. Steps are similar for the `VoiceAttack` project, except there's no properties tree, just select `Build Events` on the left if it's not already selected.

Thanks

**Comment by jvbraganca** [comment]
I changed the name of the folder and X-Plane's generated plugin to: `.\plugins\XP11_VALink\64\win.xpl` and the plugin has loaded. `Loaded: D:\Program Files (x86)/Steam/steamapps/common/X-Plane 11/Resources/plugins/XP11_VALink/64/win.xpl (ndjsoft.xp11va.connector).` (Before the change I couldn't see this line on the log).

![image](https://user-images.githubusercontent.com/16918085/103481422-b53e9c80-4db9-11eb-9ac2-43a0a35e0b9a.png)

* * *

>    1. Open Visual Studio
>    2. Right-click on the `XPlane11` project and select `Properties`
>    3. Set the configuration to `Debug` or `Release`, as you prefer
>    4. In the `Configuration Properties` tree, drill-down to `Configuration Properties > C/C++ > Preprocessor`
>    5. On the first item in the right-hand side, `Preprocessor Definitions`, click the down arrow and select `<Edit...>`
>    6. add `XPLM301` and `XPLM303` to the list, each on their own line
>    7. Close the properties pane by clicking `OK`
>    8. Rebuild by going to the `Build` menu, and selecting `Rebuild Solution`

When I tried to follow the step-by-step I couldn't see anything when I right-clicked and selected properties.


EDIT: Realised that I placed the wrong dataref, when I changed it to the correct one got another error. See below

So, changed the parameters for the heading dataref `sim/cockpit/autopilot/heading` and when I tried to make sure everything was correct with the Set Dataref function I got the following message:

![image](https://user-images.githubusercontent.com/16918085/103481719-89bcb180-4dbb-11eb-827c-6d3e2a522dc1.png)

And the content for the decimal values are

![image](https://user-images.githubusercontent.com/16918085/103481736-98a36400-4dbb-11eb-86ef-c5b58646e1c8.png)

And when I tried to run the plugin I got the error: `12:00:43.101 UNABLE TO INVOKE PLUGIN, 'X-Plane 11 / VoiceAttack Link'. DUE TO EXCEPTION: No int value assigned to datarefValue`

**Comment by nskillen** [comment]
HI @jvbraganca 

So I don't think the version up here on github is actually in a workable state😊. I've got X-Plane downloaded, and was able to build and run locally in such a fashion that things at least started to work. I haven't checked everything, but I was able to raise/lower landing gear, and get the current compass heading.

[XP11_VA_Link.zip](https://github.com/nskillen/XP11_VA_Link/files/5762407/XP11_VA_Link.zip)

This zip file contains both plugins that I was using, as well as a VoiceAttack profile that contains some pre-defined helper commands.

I've changed a fair bit about how to pass data around within VoiceAttack in this newer version. To summarize:
- The main commands you'll interact with are contained in the categories `Plugin Commands - Commands` and `Plugin Commands - Datarefs`. You can use the two items in `Plugin Commands - Internal` if you really want to, but it should be easier to use the others.
  - Plugin Commands - Commands
    - `Begin Command` starts a long-running command. That command will remain active until you send a corresponding `End Command`
    - `End Command` ends a long running command
    - `Execute Command Once` runs a command as an instant one-off. This is probably the one you'll use the most.
    - `Hold Command` runs a command for a specified amount of time.
  - Plugin Commands - Datarefs
    - `Get Dataref` gets the value of a dataref from X-Plane, and places it into `~~datarefValue` (the `~~` means the variable is scoped to the current command tree, and won't affect any other state within VoiceAttack)
    - `Set Double Dataref` sets a dataref that has a double value
    - `Set Float Dataref` sets a dataref that has a float value
    - `Set Int Dataref` sets a dataref that has an integer value
    - `Set Text Dataref` sets a dataref that has a text value
- Usage Details
  - For the `Plugin Command - Commands` actions, when you add the `Execute Command` item to your own command, at the bottom of the window you'll see a section called `Passed Values (Advanced)`. For all command actions, in the `Text` section, add the name of the command you're calling, surrounded by quotation marks (eg `"sim/flight_controls/landing_gear_up"`). This tells it what command to run. If you're calling `Hold Command`, then in the `Integers` field, enter the number of seconds to hold the command.
  - For the `Plugin Command - Datarefs` section:
    - For `Get Dataref` pass the name of the dataref in the `Text` section of passed values, wrapped in quotes like with the commands (eg `"sim/cockpit2/gauges/indicators/compass_heading_deg_mag"`). The output can be found in `~~datarefvalue`. Note that when using token substitution in strings, the data type is important. If you create an integer variable named `foo`, then `{TXT:foo}` will be unset, you have to use `{INT:foo}`. Full details on these tokens is in the voiceattack help pdf, available [here](https://voiceattack.com/VoiceAttackHelp.pdf). See the section titled `Text (and Text-To-Speech) Tokens`
    - For the various `Set <type> Dataref` commands, in addition to passing the name of the dataref as the first `Text` passed value, you also pass the value to set. In the case of another text value, separate it from the previous value with a semicolon (eg `"some/data/ref";someTextVariable`). For float or double datarefs, pass the value in the `Decimals` section. For int datarefs, in the `Integers` section. You can pass either a variable name that contains the value, or a literal value. Because thes commands know what type of dataref you're setting, you don't have to worry about `datarefType` anymore.

Here, for example is a quick command I put together to test getting a dataref:
![image](https://user-images.githubusercontent.com/120346/103491159-9d2d4400-4dde-11eb-9d35-4f0db5669b28.png)


I did see the `Unable to use plugin` message, but only once or twice, and have not been able to reliably reproduce.

**Comment by nskillen** [comment]
Oh, and the lack of anything in the `Plugins` menu (except for the `Plugin Admin` tool) is correct. The only time additional items show up there is when the plugin itself requests it, which I have not.

**Comment by jvbraganca** [comment]
Awesome @nskillen!

I will test it with some friends and will give you some feedback! But I am pretty sure things are going to work this time.

I saw that you made a PR for making the documentation better, with the answers you provided me here I am sure you can build an amazing one.

Thank you so much for the time you invested into VA Link!

**Comment by jvbraganca** [comment]
Hey @nskillen just to be sure, this is correct right?

![image](https://user-images.githubusercontent.com/16918085/103493802-3590ec00-4e12-11eb-82de-b93c42194c9b.png)

![image](https://user-images.githubusercontent.com/16918085/103493806-3aee3680-4e12-11eb-897a-22f1537ae739.png)

I am getting this error:
![image](https://user-images.githubusercontent.com/16918085/103493796-2ca01a80-4e12-11eb-855d-f093c258fd2d.png)

The helper function:

![image](https://user-images.githubusercontent.com/16918085/103493826-5ce7b900-4e12-11eb-88cb-650bf611910c.png)

Even when I try to get the dataref I still get the error saying that no datarefValue was passed.

**Comment by nskillen** [comment]
[XP11_VA_Link.zip](https://github.com/nskillen/XP11_VA_Link/files/5763188/XP11_VA_Link.zip)

I made some changes to the VoiceAttack plugin, so that when it fails it should just log the error instead of causing VoiceAttack to nuke the plugin (requiring a restart of VoiceAttack. If things worked intermittently, that may be why). In addition, something was wonky with the `Set Dataref` base command in the previous profile, so I ended up completely re-creating it. I suggest deleting all the imported commands (if you're using them) and re-importing the profile from the included zip.

I'm not sure what command you're running. Keep in mind that commands are different than datarefs, and setting a dataref generally won't require commands, and vice-versa. Commands (generally) correspond to things that are mappable to joystick inputs, eg there's `sim/flight_controls/flaps_down` which extends the flaps by one notch. That's a command, and they take no arguments.

If you want to set heading (I'm assuming you're looking at the dataref `sim/cockpit/autopilot/heading_mag`, then you'd want a simple VoiceAttack action that looks like this
![image](https://user-images.githubusercontent.com/120346/103503997-57d73980-4e13-11eb-81e3-e8c27c4c1ac9.png)
I don't have a mic for now, so I can't test the voice part, but when I replaced the `~heading` in the passed decimal with `222.0` it worked.

**Comment by crbascott** [comment]
Firstly, I want to say very nice work. I have been using the VA plugin developed by SPAD.neXt and I really like the additional functionality XP11_VA_Link provides. I will more than likely convert over to this despite already have sunken in $$$ to SN. Oh well.

I have successfully tested all primary functions (Get, Set, Command Execution) and have just one minor area of confusion. For the Get Dataref, I have noticed a second text parameter (~targetVar). It is obviously optional as ~~datarefValue works fine when not passing it. However, I have yet to figure out what is expected for ~targetVar (my C++ is pretty weak). Any insight you can share would be great.

Thanks!

**Comment by nskillen** [comment]
You don't have to put anything there. The intention with `~targetVar` is if you want to have VoiceAttack automatically place the output from the `Get Dataref` call somewhere other than `~~datarefValue`, you set `~targetVar` to some string value, and when `Get Dataref` completes, you have a variable of your own named whatever was in `~targetVar` that has the value you were after.

**Comment by crbascott** [comment]
Thanks, I assumed that’s what it was for but apparently wasn’t doing something correctly. Again, not using `~targetVar` definitely works fine. I’ll have to play around with it and see if there is an advantage (code readability?) one way or the other.

Thanks again!
